var gnames = [
    // 'aliens',
    // 'angelsdemons',
    // 'assemblyline',
    // 'avoidgeorge',
    // 'bait',
    // 'blacksmoke',
    // 'boloadventures',
    // 'bomber',
    // 'boulderchase',
    // 'boulderdash',
    'brainman',
    // 'butterflies',
    // 'cakybaky',
    // 'camelRace',
    // 'catapults',
    // 'chainreaction',
    // 'chase',
    // 'chipschallenge',
    // 'chopper',
    // 'clusters',
    // 'colourescape',
    // 'cookmepasta',
    // 'cops',
    // 'crossfire',
    // 'defem',
    // 'defender',
    // 'digdug',
    // 'dungeon',
    // 'eggomania',
    // 'enemycitadel',
    // 'escape',
    // 'factorymanager',
    // 'firecaster',
    // 'fireman',
     'firestorms',
    // 'freeway',
    // 'frogs',
    // 'gymkhana',
    // 'hungrybirds',
    // 'iceandfire',
    // 'infection',
    // 'intersection',
    // 'islands',
    // 'jaws',
    // 'labyrinth',
    // 'labyrinthdual',
    // 'lasers',
    // 'lasers2',
    // 'lemmings',
    // 'missilecommand',
    // 'modality',
    // 'myAliens',
    // 'overload',
     'pacman',
    // 'painter',
    // 'plants',
    // 'plaqueattack',
    // 'portals',
    // 'racebet',
    // 'racebet2',
    // 'realportals',
    // 'realsokoban',
    // 'rivers',
    // 'roguelike',
    // 'run',
    // 'seaquest',
    // 'sheriff',
    // 'shipwreck',
    'sokoban',
    'solarfox',
    // 'superman',
    // 'surround',
    'survivezombies',
    // 'tercio',
    // 'thecitadel',
    // 'thesnowman',
    // 'waitforbreakfast',
    // 'watergame',
    // 'waves',
    // 'whackamole',
    // 'witnessprotection',
    // 'zelda',
    'zenpuzzle',
];

function gamesToSelect() {
    var selectGames = document.getElementById('chooseGameSelect');
    for (var i = 0; i < gnames.length; i++) {
        var option = document.createElement("option");
        var name = gnames[i];
        option.value = name;
        option.text = name;
        selectGames.appendChild(option);
    }
}